version: '3.8'

services:
  # --- VCENTER 01 ---
  vcenter-01:
    build: .
    image: vmware-exporter-local:latest
    container_name: vmware-exporter-v01
    restart: unless-stopped
    ports:
      - "9169:9169"
    command:
      - "-vmware.vcenter=vcenter-01.example.com"
      - "-vmware.username=administrator@vsphere.local"
      - "-vmware.password=YOUR_PASSWORD_HERE"
      - "-vmware.insecureTLS=true"
      - "-collector.vm=true"
      - "-collector.host=true"
      - "-collector.datastore=true"
      - "-collector.cluster=true"
      - "-collector.datacenter=true"
      - "-collector.esxcli.host.nic=true"
      - "-collector.esxcli.storage=true"
      - "-vmware.interval=300"

  # --- VCENTER 02 ---
  vcenter-02:
    build: .
    image: vmware-exporter-local:latest
    container_name: vmware-exporter-v02
    restart: unless-stopped
    ports:
      - "9170:9169"
    command:
      - "-vmware.vcenter=vcenter-02.example.com"
      - "-vmware.username=administrator@vsphere.local"
      - "-vmware.password=YOUR_PASSWORD_HERE"
      - "-vmware.insecureTLS=true"
      - "-collector.vm=true"
      - "-collector.host=true"
      - "-collector.datastore=true"
      - "-collector.cluster=true"
      - "-collector.datacenter=true"
      - "-collector.esxcli.host.nic=true"
      - "-collector.esxcli.storage=true"
      - "-vmware.interval=300"
