{
 "title": "ESXi SNMP",
 "description": "A dashboard for visualizing collected ESXi hypervisor data (including hosted VMs) from the target's SNMP port using Telegraf.",
 "tags": [
  "ESXi",
  "SNMP"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Host State",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "esxi_snmp_uptime{agent_host=\"ESXI.test.com\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "Host Information",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_uptime{agent_host=\"ESXI.test.com\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_storage_size{agent_host=\"ESXI.test.com\", storage_desc=\"Real Memory\"} * esxi_snmp_storage_allocation_units{agent_host=\"ESXI.test.com\", storage_desc=\"Real Memory\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_storage_size{agent_host=\"ESXI.test.com\", storage_type=\".1.3.6.1.2.1.25.2.1.4\"} * esxi_snmp_storage_allocation_units{agent_host=\"ESXI.test.com\", storage_type=\".1.3.6.1.2.1.25.2.1.4\"}",
     "legendFormat": "{{storage_desc}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Core(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_processor_load{agent_host=\"ESXI.test.com\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "NIC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "NIC(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_nic_bytes_out{agent_host=\"ESXI.test.com\", nic_name=~\".*vmnic.*\"}",
     "legendFormat": "{{nic_name}}"
    }
   ]
  },
  {
   "title": "Host Bus Adapter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "HBA(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_hba_number{agent_host=\"ESXI.test.com\"}"
    }
   ]
  },
  {
   "title": "Virtual Machine",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "VM(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_vm_mem_size{agent_host=\"ESXI.test.com\"}",
     "legendFormat": "{{vm_display_name}}"
    }
   ]
  },
  { "title": "Resources' Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(esxi_snmp_storage_used{agent_host=\"ESXI.test.com\", storage_desc=\"Real Memory\"} / esxi_snmp_storage_size{agent_host=\"ESXI.test.com\", storage_desc=\"Real Memory\"}) * 100",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(esxi_snmp_storage_used{agent_host=\"ESXI.test.com\", storage_type=\".1.3.6.1.2.1.25.2.1.4\"}) / sum(esxi_snmp_storage_size{agent_host=\"ESXI.test.com\", storage_type=\".1.3.6.1.2.1.25.2.1.4\"})) * 100",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "title": "Processor Load (Last Minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "esxi_snmp_processor_load{agent_host=\"ESXI.test.com\"}",
     "legendFormat": "Core {{index}}"
    }
   ]
  },
  {
   "title": "NIC",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "esxi_snmp_nic_state{agent_host=\"ESXI.test.com\", nic_desc=~\".*vmnic.*\"}",
     "legendFormat": "{{nic_desc}}"
    },
    {
     "expr": "esxi_snmp_nic_speed{agent_host=\"ESXI.test.com\", nic_desc=~\".*vmnic.*\"}",
     "legendFormat": "{{nic_desc}}"
    }
   ]
  },
  {
   "title": "NIC - Input Traffic (RX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(esxi_snmp_nic_bytes_in{agent_host=\"ESXI.test.com\", nic_name=~\".*vmnic.*\"}[2m])",
     "legendFormat": "{{nic_name}}"
    }
   ]
  },
  {
   "title": "NIC - Output Traffic (TX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(esxi_snmp_nic_bytes_out{agent_host=\"ESXI.test.com\", nic_name=~\".*vmnic.*\"}[2m])",
     "legendFormat": "{{nic_name}}"
    }
   ]
  },
  {
   "title": "Resources' Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "esxi_snmp_storage_allocation_units{agent_host=\"ESXI.test.com\", storage_desc=\"Real Memory\"}",
       "legendFormat": "Allocation Unit"
      },
      {
       "expr": "esxi_snmp_storage_size{agent_host=\"ESXI.test.com\", storage_desc=\"Real Memory\"} * esxi_snmp_storage_allocation_units{agent_host=\"ESXI.test.com\", storage_desc=\"Real Memory\"}",
       "legendFormat": "Size"
      },
      {
       "expr": "esxi_snmp_storage_used{agent_host=\"ESXI.test.com\", storage_desc=\"Real Memory\"} * esxi_snmp_storage_allocation_units{agent_host=\"ESXI.test.com\", storage_desc=\"Real Memory\"}",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Storage",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "esxi_snmp_storage_allocation_units{agent_host=\"ESXI.test.com\", storage_desc!=\"Real Memory\"}",
       "legendFormat": "Allocation Unit"
      },
      {
       "expr": "esxi_snmp_storage_size{agent_host=\"ESXI.test.com\", storage_desc!=\"Real Memory\"} * esxi_snmp_storage_allocation_units{agent_host=\"ESXI.test.com\", storage_desc!=\"Real Memory\"}",
       "legendFormat": "Size"
      },
      {
       "expr": "esxi_snmp_storage_used{agent_host=\"ESXI.test.com\", storage_desc!=\"Real Memory\"} * esxi_snmp_storage_allocation_units{agent_host=\"ESXI.test.com\", storage_desc!=\"Real Memory\"}",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Storage Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(esxi_snmp_storage_used{agent_host=\"ESXI.test.com\", storage_type=\".1.3.6.1.2.1.25.2.1.4\"} / esxi_snmp_storage_size{agent_host=\"ESXI.test.com\", storage_type=\".1.3.6.1.2.1.25.2.1.4\"}) * 100",
       "legendFormat": "{{storage_desc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Bus Adapters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Bus Adapter",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "esxi_snmp_hba_bus_number{agent_host=\"ESXI.test.com\"}",
       "legendFormat": "Bus Number"
      },
      {
       "expr": "esxi_snmp_hba_status{agent_host=\"ESXI.test.com\"}",
       "legendFormat": "Status"
      }
     ]
    }
   ]
  },
  { "title": "Virtual Machines' Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_vm_mem_size{agent_host=\"ESXI.test.com\", vm_state=\"powered on\"}"
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_vm_mem_size{agent_host=\"ESXI.test.com\", vm_state=\"powered off\"}"
    }
   ]
  },
  {
   "title": "Windows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_vm_mem_size{agent_host=\"ESXI.test.com\", vm_guest_os=~\".*Windows.*\"}"
    }
   ]
  },
  {
   "title": "Debian",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_vm_mem_size{agent_host=\"ESXI.test.com\", vm_guest_os=~\".*Debian.*\"}"
    }
   ]
  },
  {
   "title": "CentOS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_vm_mem_size{agent_host=\"ESXI.test.com\", vm_guest_os=~\".*CentOS.*\"}"
    }
   ]
  },
  {
   "title": "Ubuntu",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esxi_snmp_vm_mem_size{agent_host=\"ESXI.test.com\", vm_guest_os=~\".*Ubuntu.*\"}"
    }
   ]
  },
  {
   "title": "VMs On Host",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "esxi_snmp_vm_mem_size{agent_host=\"ESXI.test.com\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "esxi_snmp_vm_num_cpu{agent_host=\"ESXI.test.com\"}",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}